[package]
name = "ultra"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
rayon = "1.8"
crossbeam = "0.8"

# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors"] }

# File watching
notify = "6.1"

# Hashing
blake3 = "1.5"

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Path utilities
path-clean = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI
clap = { version = "4.0", features = ["derive"] }

# JS/TS parsing with oxc
oxc = "0.39"
oxc_parser = "0.39"
oxc_ast = "0.39"
oxc_span = "0.39"
oxc_allocator = "0.39"

# CSS processing with lightningcss
lightningcss = "1.0.0-alpha.67"

# Additional dependencies for missing functionality
dirs = "5.0"
bincode = "1.3"
md5 = "0.7"
num_cpus = "1.16"
rand = "0.8"

# Add these to avoid compilation errors with current crate versions
# Note: These versions may need adjustment based on available crates
futures-util = "0.3"

# WebSocket for HMR
tokio-tungstenite = "0.21"

# Compression
brotli = "6.0"
zstd = "0.13"

# Memory mapping
memmap2 = "0.9"

[dev-dependencies]
tempfile = "3.8"